# Generated by Django 5.2 on 2025-04-22 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docx_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('html_file', models.FileField(blank=True, null=True, upload_to='output/%Y/%m/%d/')),
                ('images_zip', models.FileField(blank=True, null=True, upload_to='output/%Y/%m/%d/')),
            ],
        ),
    ]
