# Generated by Django 5.2 on 2025-04-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='docx_file',
            field=models.FileField(max_length=255, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='html_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='output/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='images_zip',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='output/%Y/%m/%d/'),
        ),
    ]
